[preload  storage="./data/bgimage/黑屏.png"  ]
[preload  storage="./data/bgimage/清洗贝贝1.png"  ]
[preload  storage="./data/bgimage/清洗贝贝2.png"  ]
[preload  storage="./data/bgimage/告别室.png"  ]
[preload  storage="./data/bgimage/贝贝告别仪式.png"  ]
[preload  storage="./data/fgimage/default/贝贝告别仪式_素材1.png"  ]
[preload  storage="./data/fgimage/default/贝贝告别仪式_素材2.png"  ]
[preload  storage="./data/fgimage/chara/1/张先生_哭泣.png"  ]
[preload  storage="./data/bgimage/宠物殡葬店.PNG"  ]
[return]